micronaut:
  application:
    name: live-rec-pi-api

recordings:
  root-dir: recordings

mixers:
  available:
    xr18:
      name: Behringer XR18
      host: 192.168.1.120
      osc-port: 10024
    x32rack:
      name: Behringer X32 Rack
      host: 192.168.1.121
      osc-port: 10023
